### PR TITLE
Topic/float

### PR DESCRIPTION
**Pull request by robinsdm**

### CODE REVIEW

**Comment by aj-michael** [comment]
It looks like you did not push the changes from Friday

**Comment by aj-michael** [comment]
Also, before we merge this we need to get all tests passing / delete the ones that don't apply anymore.

**Comment by aj-michael** [comment]
We should delete the out files as well as the Java files.

**Comment by aj-michael** [comment]
Also, any idea why test coverage got so much lower?

**Comment by robinsdm** [comment]
The reason the test coverage went down was I had to delete a lot of tests that don't work anymore because they assumed certain types that operates return. Also, there is a lot of code for doubles, floats, and longs that isn't tested.

**Comment by aj-michael** [comment]
I think we should add some code generator tests that cover doubles/floats/longs. It should be pretty easy, just use the programs that you manually tested with. I can't remember what number I used for the threads test.

**Comment by aj-michael** [comment]
Awesome 🚀

**Pull request merged**
